### ISSUE TITLE
Edit Pet Details - Really long text fails

### ISSUE THREAD

**Issue by rodne3** [Eorate/petsrus#52]
![Screenshot from 2020-03-20 17-54-27](https://user-images.githubusercontent.com/54286664/77176020-8712f900-6ad4-11ea-8ad0-27f82af9337d.png)

If you enter really long text for the breed eg "This is a really long name for a breed", you get the following error

```
10.0.3.1 - - [20/Mar/2020 14:54:34] "POST /pets/770 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 1835, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 1850, in finalize_request
    response = self.make_response(rv)
  File "/home/vagrant/env-py37/lib/python3.7/site-packages/flask/app.py", line 1976, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by Tharlaw** [comment]
This has been fixed and pushed to master.
